"""Added memory column

Revision ID: c9aac5fc7e72
Revises: 5fa16c82799e
Create Date: 2020-07-08 18:49:54.928335

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9aac5fc7e72'
down_revision = '5fa16c82799e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phone', sa.Column('memory', sa.Integer(), nullable=True))
    op.add_column('phone', sa.Column('ram', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phone', 'ram')
    op.drop_column('phone', 'memory')
    # ### end Alembic commands ###
